// lib/firebase_options.dart
// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5jO-i23OF8DfKaSifpW9tY6BtKmXkjOk',
    appId: '1:877689410074:web:89092bb03fa37c9128b7a3',
    messagingSenderId: '877689410074',
    projectId: 'cash-6138e',
    authDomain: 'cash-6138e.firebaseapp.com',
    storageBucket: 'cash-6138e.firebasestorage.app',
    measurementId: 'G-W2MQ50GVVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5jO-i23OF8DfKaSifpW9tY6BtKmXkjOk',
    appId: '1:877689410074:android:89092bb03fa37c9128b7a3',
    messagingSenderId: '877689410074',
    projectId: 'cash-6138e',
    storageBucket: 'cash-6138e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5jO-i23OF8DfKaSifpW9tY6BtKmXkjOk',
    appId: '1:877689410074:ios:89092bb03fa37c9128b7a3',
    messagingSenderId: '877689410074',
    projectId: 'cash-6138e',
    storageBucket: 'cash-6138e.firebasestorage.app',
    iosBundleId: 'com.nexa.novasignal',
  );
}