class AppStrings {
  static Map<String, Map<String, String>> translations = {
    'pt': {
      'app_name': 'Cabinda Shop',
      'home': 'Inicio',
      'channels': 'Loja',
      'basket': 'Cesta',
      'settings': 'Configuracoes',
      'dark_mode': 'Modo Escuro',
      'language': 'Idioma',
      'choose_language': 'Escolher Idioma',
      'portuguese': 'Portugues',
      'english': 'English',
      'help': 'Ajuda',
      'security': 'Seguranca e Privacidade',
      'account': 'Configuracoes da Conta',
      'add_to_cart': 'Adicionar ao Carrinho',
      'remove_from_cart': 'Remover do Carrinho',
      'price': 'Preço',
      'description': 'Descrição',
      'empty_cart': 'Cesta Vazia',
      'clear_cart': 'Esvaziar',
      'select_color': 'Selecionar Cor',
      'select_size': 'Selecionar Tamanho',
      'quantity': 'Quantidade',
      'total': 'Total',
      'checkout': 'Finalizar Compra',
      'product_details': 'Detalhes do Produto',
      'rating': 'Avaliação',
      'reviews': 'Avaliações',
      'availability': 'Disponibilidade',
      'in_stock': 'Em Estoque',
      'out_of_stock': 'Fora de Estoque',
      'brand': 'Marca',
      'category': 'Categoria',
      'explore_more': 'explorar mais',
    },
    'en': {
      'app_name': 'Cabinda Shop',
      'home': 'Home',
      'channels': 'Store',
      'basket': 'Basket',
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'choose_language': 'Choose Language',
      'portuguese': 'Portugues',
      'english': 'English',
      'help': 'Help',
      'security': 'Security and Privacy',
      'account': 'Account Settings',
      'add_to_cart': 'Add to Cart',
      'remove_from_cart': 'Remove from Cart',
      'price': 'Price',
      'description': 'Description',
      'empty_cart': 'Empty Basket',
      'clear_cart': 'Clear',
      'select_color': 'Select Color',
      'select_size': 'Select Size',
      'quantity': 'Quantity',
      'total': 'Total',
      'checkout': 'Checkout',
      'product_details': 'Product Details',
      'rating': 'Rating',
      'reviews': 'Reviews',
      'availability': 'Availability',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',
      'brand': 'Brand',
      'category': 'Category',
      'explore_more': 'explore more',
    },
  };

  static String get(String key, String locale) {
    return translations[locale]?[key] ?? translations['en']?[key] ?? key;
  }
}